CableApiAndroidMaster/CableApiAndroidMaster/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using CableApiAndroidMaster.Areas.HelpPage.ModelDescriptions;
using CableApiAndroidMaster.Areas.HelpPage.Models;

namespace CableApiAndroidMaster.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

CableApiAndroidMaster/CableApiAndroidMaster/Controllers/RemoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CableApiAndroidMaster.Entity;
using CableApiAndroidMaster.Models;

namespace CableApiAndroidMaster.Controllers
{
    public class RemoteController : Controller
    {

        public ActionResult SendDataIntoUrl()
        {
            return View();

        }

    }
}

CableApiAndroidMaster/CableApiAndroidMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CableApiAndroidMaster/CableApiAndroidMaster/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/styles.css" rel="stylesheet" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>


    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-dark">
        @Html.ActionLink("Sky Vision IT Solutions", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

        <div class="col-md-8">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse le" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li>@Html.ActionLink("Home", "Dashboard", "Admin", new { area = "" }, new { @class = "nav-item nav-link" })</li>
                    <li>@Html.ActionLink("Request", "RequestApproval", "Dashboard", new { area = "" }, new { @class = "nav-item nav-link" })</li>
                    <li>@Html.ActionLink("Admin Registration", "AdminRegistration", "Home", new { area = "" }, new { @class = "nav-item nav-link" })</li>
                    <li>@Html.ActionLink("Send Data", "SendDataIntoUrl", "Remote", new { area = "" }, new { @class = "nav-item nav-link" })</li>

                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="collapse navbar-collapse le" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li>@Html.ActionLink("Logout", "LogOut", "Home", new { area = "" }, new { @class = "nav-item nav-link" })</li>
                </ul>
            </div>
        </div>

    </nav>


    <div class="col-md-12 psd-padding-margin-top">
        @RenderBody()
        <hr />

        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - Sky Vision IT Solutions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>